### ISSUE TITLE
InlineFormSet has no attribute 'base_fields'

### ISSUE THREAD

**Issue by halfnibble** [vikingco/django-multipleformwizard#5]
Not sure why, but when I use an inlineformset, I get the following error:
```python
AttributeError: type object 'MyModelFormSet' has no attribute 'base_fields'
```

It appears to be choking on line 107 in views.py of this package.

```python
for field in six.itervalues(form.base_fields):
```

**Comment by dirkmoors** [comment]
Hello, thank you for your comment. Could you provide me with some example code so I can reproduce the error you're experiencing?

**Comment by dirkmoors** [comment]
(Also, if you have a suggestion for a fix, please create a pull request.)

**Comment by halfnibble** [comment]
I think the issue is that inlineformsets don't have an attribute "base_fields." From my precursory research, it looks like they have ```inlineformset.form.base_fields```. So perhaps changing the test on line 107 to account for this?

**Comment by dirkmoors** [comment]
Could you try your approach and create a pull request for it? I'll review, merge and release an update asap.

**Comment by halfnibble** [comment]
Sure thing, it is late in my timezone, but I'll add to my list for tomorrow morning.

**Comment by dirkmoors** [comment]
Awesome, thank you! I'm looking forward to your PR.

**Comment by halfnibble** [comment]
This still shows as open on github...how is that possible? I received a closed message.
